### ISSUE TITLE
Error ("boc":null) on deploying solidity helloWorld smart contract on TONLabs/local-node

### ISSUE THREAD

**Issue by dpigorev** [tonlabs/everdev#122] opened 2022-08-20 12:22 UTC
1. I've launched tonlabs/local-node image on my Desktop Docker (OS: Windows 10, Docker: v4.11.1).
Successfully started web-server.

2. Using VSCode created helloWorld contract:
```
everdev sol create helloWorld
everdev sol compile helloWorld.sol

```
While deploying contract I met some error:
`everdev c i helloWorld`

```
Configuration

  Network: se (http://localhost)
  Signer:  owner_keys (public 18c05ccc253deb1c2f3481a45f32645d66a51f6f198f1ef6811e3667d2067f30)

Address:   0:e077fd0s7a01ce9b12643fdecf24caf6cbfd39d2ca3143cbac534d8e48324020 (calculated from TVC and signer public)    
Error: Invalid parameters: invalid type: null, expected a string at line 1 column 11
params: {"boc":null}
```

**Comment by Artem-Zhdanov** [comment] 2022-08-23 13:32
I can't reproduce this bug :-(
Can we make sure that at least without VSCode everything works as it should?
Can you run in terminal:
```
 everdev se start
 everdev sol create helloWorld
 everdev sol compile helloWorld.sol 
 everdev network default se
 everdev signer add giver_keys 172af540e43a524763dd53b26a066d472a97c4de37d5498170564510608250c3
 everdev network giver se 0:b5e9240fc2d2f1ff8cbb1d1dee7fb7cae155e5f6320e585fcc685698994a19a5 --signer giver_keys
 everdev signer generate owner_keys
 everdev signer default owner_keys
 everdev contract deploy -v 10000000000 helloWorld
```

**Comment by elasticLove1** [comment] 2022-09-12 08:13
@dpigorev

**Comment by elasticLove1** [comment] 2022-10-20 16:20
This was a bug in the SE. Fixed in the last SE release.

**Closed** 2022-10-20 16:21 UTC
